#!/bin/bash
source /home/work/.bash_profile
host="ipA ipB ipC"
for h in ${host}
do
        echo "!!!!!!Start to deploy $h !!!!!!!"
        hname=`echo "${h}" | awk -F'.' '{print $3}'`
        echo "Send wars to server..."    
        scp ~/downloads/${hname}.`date +%Y-%m-%d`.war work@$h:~/downloads/${hname}.`date +%Y-%m-%d`.war
        sleep 2
        ssh work@$h 'bash -s' < restart.sh ${hname}
        sleep 5
done

